### ISSUE TITLE
Only ‘=‘ when initializing new variables 

### ISSUE THREAD

**Issue by nikeedev** [StioStudio/stio_studio#1]
I saw you said that when initializing a variable you can use +=, -=, *=, /=, and =. 

I think you should have said that you can do only do = when initializing and the other and = when you modifying or changing the value.

**Comment by StioStudio** [comment]
> I saw you said that when initializing a variable you can use +=, -=, *=, /=, and =.
> 
> I think you should have said that you can do only do = when initializing and the other and = when you modifying or changing the value.

No, it will work. += Whouled have been like 0+value. -= whouled be 0-value

**Comment by nikeedev** [comment]
Okay 👍, also a question, what is the default empty type gonna be called (like `undefined` in js, `nil` in some other languages, `none` in V, or even `empty` in some other language)

**Comment by StioStudio** [comment]
> Okay 👍, also a question, what is the default empty type gonna be called (like `undefined` in js, `nil` in some other languages, `none` in V, or even `empty` in some other language)

Maybe undefined, but I will add the others too

**Comment by nikeedev** [comment]
Can I contribute to the repo? 
so that I can fix on some stuff that maybe could be useful

**Comment by nikeedev** [comment]
But if you like the PR I sent, accept it and push

**Comment by StioStudio** [comment]
> But if you like the PR I sent, accept it and push

I am on my phone, so I will do it later :)
